#!/bin/bash
## Jobname
#SBATCH --job-name=20181026-fish-fastqc
## Allocation Definition
#SBATCH --account=stf
#SBATCH --partition=stf
## Resources
## Nodes
#SBATCH --nodes=1
## Walltime
#SBATCH --time=2:00:00 (hours, 3 hrs, hyak max = 30 days)
## Memory per node
#SBATCH --mem=100G
## Specify the working directory for this job
#SBATCH --workdir=/gscratch/stf/kimh11/fish-fastqc
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kimh11@uw.edu
## export all your environment variables to the batch job session
#SBATCH --export=all
